vector_template: vector-beyond.toml.j2
vector_config_file: /etc/vector/vector.toml
vector_nightly: no
vector_version: "{{ vector_nightly | ternary('nightly','latest') }}"
add_vector_docker_group: no # Add vector user to "docker" group
add_vector_journal_group: no # Add vector user to "systemd-journal" group

sources:
  journald:
    type: journald
    current_boot_only: true
      - journald
sinks:
  console:
    type: console
    inputs:
      - journald
    encoding.codec: json

